### PR TITLE
Add support for Philips Hue Smart Button

### LINKED ISSUE #68: Controller blueprint for Philips Hue Smart Button
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to propose a new blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Description\*

Support for the [Philips Hue Smart Button](https://www.philips-hue.com/en-us/p/hue-smart-button/046677553715)
I can help test/debug with ZHA.

## Implementation

I'll leave this to @EPMatt, a good dev and a kind person. :)

Here are the events captured via ZHA:

- Short Press:
```
Event 2 fired 13:12:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0x0006",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "off_with_effect",
        "args": [
            0,
            0
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:12:24.207368+00:00",
    "context": {
        "id": "c10abd0a1e22778f3ffc3b67bc0ea1a8",
        "parent_id": null,
        "user_id": null
    }
}
Event 1 fired 13:12:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_press",
        "args": {
            "button": "on",
            "press_type": "press",
            "command_id": 0,
            "args": [
                1,
                3145728,
                0,
                33,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:12:24.140272+00:00",
    "context": {
        "id": "1282b8d1f1e1c3a3a7c52ba7fbc203b5",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 13:12:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_short_release",
        "args": {
            "button": "on",
            "press_type": "short_release",
            "command_id": 0,
            "args": [
                1,
                3145728,
                2,
                33,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:12:23.905872+00:00",
    "context": {
        "id": "6f9efa9c8b103a1672a6de68200ae940",
        "parent_id": null,
        "user_id": null
    }
}
```

- Long Press:
```
Event 5 fired 13:15:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0x0008",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "stop",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:15:47.001521+00:00",
    "context": {
        "id": "866ac2a114985a76df8595ca26aace15",
        "parent_id": null,
        "user_id": null
    }
}
Event 4 fired 13:15:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_long_release",
        "args": {
            "button": "on",
            "press_type": "long_release",
            "command_id": 0,
            "args": [
                1,
                3145728,
                3,
                33,
                12,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:15:46.983974+00:00",
    "context": {
        "id": "1b4b1810da22f67d85cbbe8a3b02f9aa",
        "parent_id": null,
        "user_id": null
    }
}
Event 3 fired 13:15:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0x0008",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "step",
        "args": [
            1,
            56,
            9
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:15:46.973192+00:00",
    "context": {
        "id": "ef4c84172e8b2d7b63112419aa2a2d88",
        "parent_id": null,
        "user_id": null
    }
}
Event 2 fired 13:15:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_hold",
        "args": {
            "button": "on",
            "press_type": "hold",
            "command_id": 0,
            "args": [
                1,
                3145728,
                1,
                33,
                8,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:15:46.557699+00:00",
    "context": {
        "id": "d51041c679b12028c6386768710c73d3",
        "parent_id": null,
        "user_id": null
    }
}
Event 1 fired 13:15:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0x0008",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "step",
        "args": [
            1,
            30,
            9
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:15:46.125730+00:00",
    "context": {
        "id": "a6945edd98872408ae9e49a0030caa0a",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 13:15:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_press",
        "args": {
            "button": "on",
            "press_type": "press",
            "command_id": 0,
            "args": [
                1,
                3145728,
                0,
                33,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:15:46.044413+00:00",
    "context": {
        "id": "104adc1c91867ea8d743fdf71386ab37",
        "parent_id": null,
        "user_id": null
    }
}
```
- Double Press:
```
Event 3 fired 13:17:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0x0006",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "off_with_effect",
        "args": [
            0,
            0
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:17:56.948705+00:00",
    "context": {
        "id": "63666c84509a66f858e028661086e97f",
        "parent_id": null,
        "user_id": null
    }
}
Event 2 fired 13:17:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_double_press",
        "args": {
            "button": "on",
            "press_type": "double_press",
            "command_id": 0,
            "args": [
                1,
                3145728,
                0,
                33,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:17:56.886489+00:00",
    "context": {
        "id": "ad4c8f1cf977adcd3bf0af175b1562bf",
        "parent_id": null,
        "user_id": null
    }
}
Event 1 fired 13:17:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_short_release",
        "args": {
            "button": "on",
            "press_type": "short_release",
            "command_id": 0,
            "args": [
                1,
                3145728,
                2,
                33,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:17:56.642102+00:00",
    "context": {
        "id": "181548aa515db31cad60cdd7a4e28f13",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 13:17:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_short_release",
        "args": {
            "button": "on",
            "press_type": "short_release",
            "command_id": 0,
            "args": [
                1,
                3145728,
                2,
                33,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:17:56.439965+00:00",
    "context": {
        "id": "65d8bccd554a5ceb2ba115bca182c30b",
        "parent_id": null,
        "user_id": null
    }
}
```
- Triple Press:
```
Event 5 fired 13:19:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0x0006",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "off_with_effect",
        "args": [
            0,
            0
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:19:09.808878+00:00",
    "context": {
        "id": "a9461ba63147883221b379210c5b5d57",
        "parent_id": null,
        "user_id": null
    }
}
Event 4 fired 13:19:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_triple_press",
        "args": {
            "button": "on",
            "press_type": "triple_press",
            "command_id": 0,
            "args": [
                1,
                3145728,
                0,
                33,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:19:09.724695+00:00",
    "context": {
        "id": "a077119e49ab5cbdec492489060bcb36",
        "parent_id": null,
        "user_id": null
    }
}
Event 3 fired 13:19:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_short_release",
        "args": {
            "button": "on",
            "press_type": "short_release",
            "command_id": 0,
            "args": [
                1,
                3145728,
                2,
                33,
                1,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:19:09.505610+00:00",
    "context": {
        "id": "9a9580f51fdc6cbfcfc0aed43cf4a7a9",
        "parent_id": null,
        "user_id": null
    }
}
Event 2 fired 13:19:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0x0006",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "on",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:19:09.455537+00:00",
    "context": {
        "id": "72d45ef80c43b51425d46f9d40966873",
        "parent_id": null,
        "user_id": null
    }
}
Event 1 fired 13:19:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_short_release",
        "args": {
            "button": "on",
            "press_type": "short_release",
            "command_id": 0,
            "args": [
                1,
                3145728,
                2,
                33,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:19:09.156316+00:00",
    "context": {
        "id": "7f237ad388947d17b7a8b45f843c9c59",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 13:19:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:08:01:9d:c6",
        "unique_id": "00:17:88:01:08:01:9d:c6:1:0xfc00",
        "device_id": "4dadf10a8f3c9622ba53aff053a732c8",
        "endpoint_id": 1,
        "cluster_id": 64512,
        "command": "on_short_release",
        "args": {
            "button": "on",
            "press_type": "short_release",
            "command_id": 0,
            "args": [
                1,
                3145728,
                2,
                33,
                0,
                0
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-19T11:19:08.952849+00:00",
    "context": {
        "id": "3a4d5d9d9bf33de24f4079824071192e",
        "parent_id": null,
        "user_id": null
    }
}
```

## Additional Details\*

- [x] I'd like to help developing this blueprint
- [x] I've found a blueprint/automation not included in this project which achieves the same/similar goal
  - Link to the resources you've found: [ControllerX data for the controller](https://xaviml.github.io/controllerx/controllers/8718699693985)

### PR DESCRIPTION
**Pull request by EPMatt**
Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Proposed change\*

Add Philips Hue Smart Button controller blueprint.
Add Light and Media Player Hooks (limited) support for the new device.
Currently only a limited set of actions is mapped to this controller for the Light and Media Player hooks, since brightness/color/volume control with the single button of this device need additional work in the hooks' implementation.

closes #68 

## Checklist\*

- [X] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [ ] I properly tested proposed changes on my system and confirm that they are working as expected.
- [X] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

### CODE REVIEW

**Comment by EPMatt** [comment]
Hi @alexdelprete,

could you please test the blueprint on your system and check if it's working as expected?
Moreover, if you have the chance to test both the Light and Media Player hook with this device, it would be really helpful.

Thank you!

**Comment by alexdelprete** [comment]
Thanks Matteo. When the kids go to bed this evening I'll have some time to do proper testing. I never tested the media player hook, but I'll see what I can do about it. :)

**Comment by alexdelprete** [comment]
@EPMatt I wanted to test the integration, but I'm blocked at the importing phase of the controller blueprint:

image

**Comment by EPMatt** [comment]
Hi @alexdelprete,

that's a strange error, since the `controller_entity` input is correctly defined in the blueprint.
Please try to delete the media player hook first, then import it again with the provided link.

Thank you! :)

**Comment by alexdelprete** [comment]
> Hi @alexdelprete,
> 
> that's a strange error, since the `controller_entity` input is correctly defined in the blueprint.
> Please try to delete the media player hook first, then import it again with the provided link.

I reimported both light & media player hooks: same error when importing the controller at that link. 
I also tried removing light & mp hooks, then import the controller, same error.

The only thing I could think of is that I'm on HA 7.0 beta...but I've imported other blueprints with no particular issues.

**Comment by alexdelprete** [comment]
Matteo,

I tried importing this: https://github.com/EPMatt/awesome-ha-blueprints/blob/implement-68/blueprints/controllers/ikea_e1744/ikea_e1744.yaml

And it worked fine. So I looked at the code, and I noticed it contains this:

`    controller_entity:
      name: (Zigbee2MQTT) Controller Entity
      description: The action sensor of the controller to use for the automation. Choose a value only if the remote is integrated with Zigbee2MQTT.
      default: ''
      selector:
        entity:
          domain: sensor`

While in the Philips Hue file I don't see that section. Could it be the problem?

**Comment by EPMatt** [comment]
Hi @alexdelprete,

> While in the Philips Hue file I don't see that section. Could it be the problem?

Exactly, the `controller_entity` input is not included in the blueprint since we don't have support for Zigbee2MQTT, but there are some parts of the code which references it.

Thank you for spotting it, I was checking the Light and Media Player hooks instead of the controller blueprint. :)

**Comment by EPMatt** [comment]
@alexdelprete here's the fix, now the controller blueprint should work as expected. 👍🏻

**Comment by alexdelprete** [comment]
> Thank you for spotting it, I was checking the Light and Media Player hooks instead of the controller blueprint. :)

No problem. Now I can import it. Will test and report back.

Thank you.

**Comment by alexdelprete** [comment]
Feedback:

- light: the controller works for single press, double press and logn press, I tried the same action (toggle light) for all thre types of events. Seems to work ok.

- media hook: I configured it for the first time, see below, but the volume didn't turn up/down for the tv. I tried it manually using the dev tools calling the service and it works. So something's not working there. Here's the media hook config and the automation trace.

image
image

**Comment by EPMatt** [comment]
Hi @alexdelprete,

sorry for my late response, and thank you for your precious feedback.

Here's the actions list available for this controller, taken from the new docs page:

> ## Available Hooks
> 
> ### Light
> 
> This Hook blueprint allows to build a controller-based automation to control a light. Supports brightness and color control both for white temperature and rgb lights.
> 
> - Button short press -> Toggle
> 
> 
> ### Media Player
> 
> This Hook blueprint allows to build a controller-based automation to control a media player. Supports volume setting, play/pause and track selection.
> 
> - Button short press -> Play/Pause
> - Button double press -> Next Track
> 

So it seems to me that the controller blueprint and hooks are working as expected. :)

Unfortunately, there's no brightness/volume control implemented yet, since a little bit of work is required in the hooks to implement it (we have only a long press action available for this device, not two as for more complex controllers). That's why hooks for now have "poor" support for this new controller.

Anyway, if it's okey for you I'd proceed to merge this PR to make the controller available to the public. We'll then work on adding support for additional hooks actions.

Thank you!

**Comment by alexdelprete** [comment]
> Anyway, if it's okey for you I'd proceed to merge this PR to make the controller available to the public. We'll then work on adding support for additional hooks actions.

I agree Matteo. Thanks again for your work.

**Pull request merged**
