### PR TITLE
Add support for Osram SMART+ Switch Mini 

### LINKED ISSUE #65: Controller blueprint for OSRAM Smart+ Switch Mini
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to propose a new blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Description\*

Controller blueprint for the [OSRAM Smart+ Switch Mini](https://www.amazon.it/gp/product/B074PZKX4G/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1) (AC025XX00NJ).

The controller comes in different colors, with different model names: AC0251100NJ / AC0251400NJ / AC0251600NJ / AC0251700NJ.

Suggestion received on the [HA Community Forum](https://community.home-assistant.io/t/zha-deconz-zigbee2mqtt-ikea-e1743-on-off-switch-dimmer-universal-blueprint-all-actions-double-click-events-control-lights-media-players-and-more-with-hooks/277861/42).

## Additional Details\*

- [X] I'd like to help developing this blueprint
- [X] I've found a blueprint/automation not included in this project which achieves the same/similar goal
  - [Z2M blueprint for the OSRAM Smart+ Switch Mini](https://community.home-assistant.io/t/zigbee2mqtt-osram-smart-switch-mini-ac0251100nj-ac0251700nj-actions/263589)

### PR DESCRIPTION
**Pull request by EPMatt**
Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Proposed change\*

Add support for Osram SMART+ Switch Mini.
Closes #65.

## Checklist\*

- [X] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [ ] I properly tested proposed changes on my system and confirm that they are working as expected.
- [X] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

### CODE REVIEW

**Comment by EPMatt** [comment]
Hi @alexdelprete,

So here we go, the blueprint is ready for testing. :) 
You can import it in your instance with the following link:

https://github.com/EPMatt/awesome-ha-blueprints/blob/osram_ac025xx00nj/blueprints/controllers/osram_ac025xx00nj/osram_ac025xx00nj.yaml

I've also added support for this controller in the Light and Media Player hooks. If you have time to test hooks as well, you can import the updated blueprints via the following links:

https://github.com/EPMatt/awesome-ha-blueprints/blob/osram_ac025xx00nj/blueprints/hooks/light/light.yaml

https://github.com/EPMatt/awesome-ha-blueprints/blob/osram_ac025xx00nj/blueprints/hooks/media_player/media_player.yaml

Please let me know if everything works as expected. :)

**Comment by alexdelprete** [comment]
Thanks a lot Matteo, you shouldn't have worked on it on Sunday, there was no rush. :)

I installed the blueprint, and the hooks, configured the automation with all the options in the controller automation and the hook automation, but it's not working. The zha events are catched by the automation, but no action has been performed.

I configured the helper last_event, even if I didn't find an explanation in the docs on your site, but I think I understood why it's needed. But I prefer to be sure. :)

I tried disabling the light hook to see if that was the problem, but it doesn't work even with just the controller automation.

I'll show you some screenshots, tell me what to do to debug the issue and I'll do it immediately. I included a trace screenshot, you can see the "no action taken" as last step, but I don't understand why.

image
image
image

**Comment by EPMatt** [comment]
Hi @alexdelprete, thank you for your detailed feedback.

> Thanks a lot Matteo, you shouldn't have worked on it on Sunday, there was no rush. :)

Don't worry. :)

It looks like there was an issue with the ZHA events we defined in the blueprint. The ones from ControllerX documentation were wrong (the prefix `1_`, `2_`, `3_` is not part of the RAW event itself).

Googling around I was able to spot the original ZHA events for this controller; I've just updated the blueprint with the correct action mappings.

It should be working now, let me know if the latest fix solves your issue. :)

> I configured the helper last_event, even if I didn't find an explanation in the docs on your site, but I think I understood why it's needed. But I prefer to be sure. :)

The config looks good to me. The explanation for the `helper_last_controller_event` input can be found in the blueprint's Additional Notes, but since this is a new device there's no doc page for this blueprint yet. :)  Here's the relevant section taken from the E1812 blueprint docs:
https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1812#additional-notes

> The `helper_last_controller_event` text input allows to store the previous button event as well as the last time a controller event was fired. This info is used in many different ways to implement the blueprint's core functionality. Make sure the input text is not altered by any other agents, since this could break the automation and lead to unexpected behaviour.

By the way, I agree that detailed and updated info regarding the `helper_last_controller_event` should be included in the [general Controllers-Hooks documentation page](https://epmatt.github.io/awesome-ha-blueprints/docs/controllers-hooks-ecosystem). :)

**Comment by alexdelprete** [comment]
Thanks Matteo, I didn't know the correct procedure to reimport it, so I deleted the previous blueprint and recreated it from scratch. Don't know if there's a better way to let an existing blueprint refresh from the URL, they should put a blueprint version next to it to distinguish. :)

Unfortunately it still doesn't work. Same thing: "no actions taken". If you need some debug info let me know what do I have to do.

image

**Comment by EPMatt** [comment]
Hi @alexdelprete,

> Thanks Matteo, I didn't know the correct procedure to reimport it, so I deleted the previous blueprint and recreated it from scratch. Don't know if there's a better way to let an existing blueprint refresh from the URL, they should put a blueprint version next to it to distinguish and a "refresh from URL" button. :)

Unfortunately that's the only way to update the blueprint for now, I hope they'll implement a better way to update blueprints from the UI one day. :) 

If you're available and have some time, we should check the ZHA events your controller is firing when interacting with it.
Please navigate to Developer Tools → Events, then in the Listen for events form type `zha_event` and click on Start Listening. Press the button on the remote, then you should instantly see the event fired by your remote.

Repeat the operation for the three buttons (up/down/circle) and for all the possible actions (short press/long press/release after long press). Then, post the events you received here.

Thank you for your help! :)

**Comment by alexdelprete** [comment]
Matteo, when testing to catch the events as you asked, I noticed that now the 1st and 3rd button (UP and DOWN) are doing what I configured in the actions (brightness+, brightness-). When I tested the automation right after upgrading to last version, they didn't work, maybe HA needs some time for internal things, don't know. But those 2 buttons are working now. :)

Anyhow, I captured all three like you asked, and I noticed that the 2nd button (that it's not working) generates two events, not one. Maybe that's the reason, I don't know.

1st button, UP:

```
Event 0 fired 3:08 PM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:0e:11:09:a6",
        "unique_id": "00:0d:6f:00:0e:11:09:a6:1:0x0006",
        "device_id": "5143a98bef16e24cda71cc3490d966d1",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "on",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-17T13:08:29.853184+00:00",
    "context": {
        "id": "2c80683ad0ca5735380752c6fbf95ea2",
        "parent_id": null,
        "user_id": null
    }
}
```

2nd button, CIRCLE:

```
Event 1 fired 3:10 PM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:0e:11:09:a6",
        "unique_id": "00:0d:6f:00:0e:11:09:a6:3:0x0008",
        "device_id": "5143a98bef16e24cda71cc3490d966d1",
        "endpoint_id": 3,
        "cluster_id": 8,
        "command": "move_to_level_with_on_off",
        "args": [
            254,
            10
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-17T13:10:21.296064+00:00",
    "context": {
        "id": "fe8d4c3df5e0b34e257d083912636fc8",
        "parent_id": null,
        "user_id": null
    }
}

Event 2 fired 3:10 PM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:0e:11:09:a6",
        "unique_id": "00:0d:6f:00:0e:11:09:a6:3:0x0300",
        "device_id": "5143a98bef16e24cda71cc3490d966d1",
        "endpoint_id": 3,
        "cluster_id": 768,
        "command": "move_to_color_temp",
        "args": [
            370,
            10
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-17T13:10:22.244946+00:00",
    "context": {
        "id": "4e27b784307bf42c526e179039f38aff",
        "parent_id": null,
        "user_id": null
    }
}
```

3rd button, DOWN:

```
Event 3 fired 3:12 PM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:0e:11:09:a6",
        "unique_id": "00:0d:6f:00:0e:11:09:a6:2:0x0006",
        "device_id": "5143a98bef16e24cda71cc3490d966d1",
        "endpoint_id": 2,
        "cluster_id": 6,
        "command": "off",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-17T13:12:44.767423+00:00",
    "context": {
        "id": "15e6753aad5dd5b7198d3101543b6a78",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by EPMatt** [comment]
Hi @alexdelprete,

thank you for your tests. It looks your controller is firing events as expected. :) 
I've just pushed an update which should solve this issue: I'm excluding the `args` event field from the definition of `trigger_action` for ZHA since it's not needed for any of the events this device fires.

Please let me know if everything runs as expected after updating the blueprint.
Thank you!

**Comment by alexdelprete** [comment]
> Please let me know if everything runs as expected after updating the blueprint.

It woooooooooooorks!!!! 😃 

So it was not the fact that it fired 2 events, but it had the args not empty.

I tested the lights hook, it's working, I would only suggest to consider changing this "steps" approach to a simpler % value. I know it's the same thing, but I think it's easier to understand at a first read. :)

image

Amazing job Matteo. Don't know how to thank you enough. I'll finally make order in my automations list. :)

**Comment by alexdelprete** [comment]
> The explanation for the `helper_last_controller_event` input can be found in the blueprint's Additional Notes, but since this is a new device there's no doc page for this blueprint yet. :) Here's the relevant section taken from the E1812 blueprint docs:

That option is general, and it's not related to a specific controller but needed for your automation to work, it should be explained in the general page of the Controller automation. Like you said in the end of the post. :)

**Pull request merged**
