### PR TITLE
Add a second mapping for IKEA E2001/E2002

### PR DESCRIPTION
**Pull request by tonynieman**
Add a second mapping for IKEA E2001/E2002 STYRBAR Remote control

## Proposed change\*
Adds a secondary mapping like the #2 of "Controller - IKEA E1743 TRÅDFRI On/Off Switch & Dimmer"
This makes it easier to controll the brightness, because the long press will allways skip more than one step (tested with zigbee2mqtt)

Mapping #2​
changes:
    Down button short press -> Brightness down
    Up button short press -> Brightness up
added:
    Up button double press -> Turn on
    Down button double press -> Turn off

rest unchanged

## Checklist\*

- [x] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [x] I properly tested proposed changes on my system and confirm that they are working as expected.
- [o] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request. (sry I do not know much about this)

### CODE REVIEW

**Comment by EPMatt** [comment]
Hi @tonynieman,

thank you so much for your contribution! Don't worry about failing checks - I'm still testing out the new CI for Pull Requests and a few issues still need to be addressed. :) 

> (sry I do not know much about this)

Don't worry, unfortunately Contribution Guidelines are outdated and do not describe how to run checks and formatters (I'm in the process of updating them as described in #192), but luckily your contribution is already properly formatted so checks should pass. :)

**Review by EPMatt — CHANGES_REQUESTED** [review]
Nice job @tonynieman! 🚀 

Could you please also update the Light Hook version in the blueprint description to the current date (`2021.11.29`) and add an entry to the Light Hook changelog in the docs ([here the file on the main branch](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/website/docs/blueprints/hooks/light.mdx))?

Thank you so much for your precious time! :)

**Comment by EPMatt** [comment]
Hi @tonynieman,

I helped you with the rebase of this Pull Request; now your branch includes changes I pushed on the `main` branch to fix those annoying failing checks which weren't related to your contribution. As a result, all checks pass now! :) 

If you need anything, such as additional guidance or support, to work on this Pull Request, I'd be glad to help you as I can.

As soon as we implement changes described in my review, your contribution can be merged and made available to the public. :)  

Thank you again for your time!

**Comment by tonynieman** [comment]
> Nice job @tonynieman! 🚀
> 
> Could you please also update the Light Hook version in the blueprint description to the current date (`2021.11.29`) and add an entry to the Light Hook changelog in the docs ([here the file on the main branch](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/website/docs/blueprints/hooks/light.mdx))?
> 
> Thank you so much for your precious time! :)

Hi, 
I added the entry. Thank you for your commitment!

Greets

**Review by EPMatt — APPROVED** [review]

**Comment by EPMatt** [comment]
Hi @tonynieman,

thank you so much for your submission! I've just sorted mappings you provided and bumped the blueprint version to the current date (2021-12-05). I'm now merging this PR in `main` along with #206 which includes documentation changes. :)

Thank you so much for your precious contribution to the project! 🚀

**Pull request merged**
