### PR TITLE
Add support for IKEA E2001/E2002 STYRBAR Remote control

### LINKED ISSUE #94: New Controller - Ikea STYRBAR E2001/E2002
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to propose support for a a new Controller blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Controller Information\*

- Manufacturer: IKEA
- Model: E2002
- Short Description: STYRBAR 4 Button Remote
- Image: 
styrbar

## Actions

If possible, provide here mappings for actions which can be triggered with this controller.
Specify the integration these mappings refer to. If you want to provide mappings for multiple integrations, you can duplicate the following section as needed.

### [Integration] ZHA

- `action_name (e.g. button_press)`: action description (e.g. sent when pressing the button)
- etc.

## Additional Details\*

Similar function to the Tradfri 5 button remote, except short press of big sun turns light on, short press of little sun turns light off.  Long presses dim up/down.

- [ ] I'd like to help developing this blueprint
- [ ] I've found a blueprint/automation not included in this project which integrates this controller
  - Link to the resources you've found: [Resource name here](https://link-goes-here)

## Additional context

Add any other context about the controller here (pitfalls in the device, checks which should be implemented to provide a fully working integration for the device, etc.).

### LINKED ISSUE #148: New Controller - IKEA Styrbar
### Manufacturer

IKEA

### Model

E2001/E2002

### Short Description

TRÅDFRI STYRBAR remote control

### Image

E2001-E2002
styrbar-fjaerrkontroll-vit__0956695_pe804773_s5

### [Integration] (e.g. deCONZ, ZHA, Zigbee2MQTT)

- `action_name (e.g. button_press)`: action description (e.g. sent when pressing the button)
- etc.

### Additional Details

- [ ] I'd like to help developing this blueprint.

### Useful resources

Zigbee2MQTT doc
https://www.zigbee2mqtt.io/devices/E2001_E2002.html#ikea-e2001%252Fe2002

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by EPMatt**
Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Proposed change\*

Add support for IKEA E2001/E2002 STYRBAR Remote control.
Closes #148.
Closes #94.

## Checklist\*

- [X] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [ ] I properly tested proposed changes on my system and confirm that they are working as expected.
- [X] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

### CODE REVIEW

**Comment by EPMatt** [comment]
Hi @andersr8n @bboti86 @arbigator,

here's the long-awaited blueprint for the IKEA E2001/E2002. :) 

Could you please test the blueprint on your system and check if it's working as expected?
Moreover, it would be amazing if you could also test the updated light and media player hooks, which now include mappings for this device.

You can import the updated blueprints via the following links:

IKEA E2001/E2002 Controller:
https://github.com/EPMatt/awesome-ha-blueprints/blob/ikea_e2001_e2002/blueprints/controllers/ikea_e2001_e2002/ikea_e2001_e2002.yaml

Light Hook:
https://github.com/EPMatt/awesome-ha-blueprints/blob/ikea_e2001_e2002/blueprints/hooks/light/light.yaml

Media Player Hook:
https://github.com/EPMatt/awesome-ha-blueprints/blob/ikea_e2001_e2002/blueprints/hooks/media_player/media_player.yaml

Here are the available actions for the Light and Media Player hooks, taken from the new device's docs page:

> ## Available Hooks
>
>### Light
>
>This Hook blueprint allows to build a controller-based automation to control a light. Supports brightness and color control both for white temperature and rgb lights.
>
>#### Default Mapping
>
>- Up button short press -> Turn on
>- Up button long press -> Brightness up (continuous, until release)
>- Down button short press -> Turn off
>- Down button long press -> Brightness down (continuous, until release)
>- Left button short press -> Color down
>- Left button long press -> Color down (continuous, until release)
>- Right button short press -> Color up
>- Right button long press -> Color up (continuous, until release)
>
>[Light Hook docs](/docs/blueprints/hooks/light)
>
>### Media Player
>
>This Hook blueprint allows to build a controller-based automation to control a media player. Supports volume setting, play/pause and track selection.
>
>#### Default Mapping
>
>- Up button short press -> Play/Pause
>- Up button long press -> Volume up (continuous, until release)
>- Down button short press -> Stop
>- Down button long press -> Volume down (continuous, until release)
>- Left button short press -> Previous track
>- Right button short press -> Next track
>
>[Media Player Hook docs](/docs/blueprints/hooks/media_player)

If tests confirm the blueprint is working as expected, we can merge this PR into `main` and make the new blueprint available to the public.

Thank you for your precious help! 👍🏻

**Comment by andersr8n** [comment]
Hi Matteo,

Sounds great. 
I will run some tests during the day. 

Anders

**Comment by gottgenk** [comment]
Works perfectly, just tested the blueprint + the light hook!

**Comment by EPMatt** [comment]
Hi @gottgenk,

thank you so much for your tests! I'm glad to hear that everything works as expected. :) 
@andersr8n @bboti86 @arbigator since we received positive feedback regarding these updates, I'm now proceeding to merge this PR into `main`, making our changes available to the public. 🎉 

Thanks again for your precious help and feedback!

**Pull request merged**
