### PR TITLE
Add ZHA release action mappings for IKEA E1810

### LINKED ISSUE #93: IKEA E1810 long press keeps looping with Light controller-hook
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to report a bug with a blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Bug Details\*

- Blueprint name: Hook - Light + Controller - IKEA E1524/E1810 5-Button Remote
- Home Assistant Core Version: 2021.6.5
- Home Assistant Installation: Type Home Assistant OS

## Description\*

I create an automation for an IKEA E1810 5-Button remote and use the Light hook to control an IKEA TRADFRI bulb E27 CWS opal 600lm. The automation should change hue/sat when pressing left/right and changing brightness when pressing up/down. This works, except when holding the left or right button. Even when holding for 1 second the automation does not seem to *catch* the release of the button because it keeps changing the light color enlessly. Short pressing the same button ends the loop.

## Automation YAML config\*
The automation for the controller:
```yaml
alias: IKEA RGB CWS with 5-Button Remote (TEMP)
description: ''
use_blueprint:
  path: EPMatt/ikea_e1524_e1810.yaml
  input:
    integration: ZHA
    controller_device: 2db9252e1f360e9a01449e49cd29db3d
    helper_last_controller_event: input_text.ikea_5_button_remote_1
    button_left_long_max_loop_repeats: 10
    button_right_long_max_loop_repeats: 10
    button_up_long_max_loop_repeats: 10
    button_down_long_max_loop_repeats: 10
    button_down_long_loop: true
    button_up_long_loop: true
    button_right_long_loop: true
    button_left_long_loop: true
```
The automation for the light:
```yaml
alias: Hook - Light
description: ''
use_blueprint:
  path: EPMatt/light.yaml
  input:
    light_color_mode: Hue - Saturation
    controller_device: 2db9252e1f360e9a01449e49cd29db3d
    controller_model: IKEA E1524/E1810 5-Button remote
    light: >-
      light.ikea_of_sweden_tradfri_bulb_e27_cws_opal_600lm_60ea21fe_level_light_color_on_off
    smooth_power_off: false
```

## To Reproduce\*

Steps to reproduce the issue:

1. Center press the controller to turn on the light: the light turns on
2. One of multiple short press left or right: the color changes in small steps
3. Long press left or right (1 or 2 seconds): the color keeps changing
4. Short press left or right: the color change cycle stops

## Expected behavior\*

The color should change while holding down the left or right button but should immediately stop changing when letting go of that button.

## Actual Behaviour\*

The color of the light keeps changing.

## Additional Details\*

When short pressing the right button the entity for *Helper - Last Controller Event* gets a single update:
```
{"trigger_action": "press_256_13_0", "last_triggered": "2021-06-20 09:26:55.527544+02:00"}
```
When long pressing the right button it gets two updates,
```
{"trigger_action": "hold_3328_0", "last_triggered": "2021-06-20 09:28:16.288400+02:00"}
{"trigger_action": "release_1159", "last_triggered": "2021-06-20 09:28:17.450062+02:00"}
``` 
So it looks like the release is not correctly processed by the automation?

I did try the *remove battery for a few minutes* trick, but that did not solve the behavior.

### PR DESCRIPTION
**Pull request by EPMatt**
Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Proposed change\*

closes #93.

## Checklist\*

- [X] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [ ] I properly tested proposed changes on my system and confirm that they are working as expected.
- [X] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

### CODE REVIEW

**Comment by EPMatt** [comment]
Hi @lebeno,

could you please test the updated blueprint? You can import it on your HA instance via the following link:

https://github.com/EPMatt/awesome-ha-blueprints/blob/fix-93/blueprints/controllers/ikea_e1524_e1810/ikea_e1524_e1810.yaml

Thank you for your patience. :)

**Comment by lebeno** [comment]
Sorry for the late reply, but using this blueprint does not fix the issue. Same problem. Please advise how to debug and provide you with more info/logs.

**Comment by EPMatt** [comment]
Hi @lebeno, thank you for the feedback. Don't worry about it, sorry for my delay. :) 

Let's consider only the left arrow button, since the fix should apply also to the right one. Please try to long press and hold the  button, then release it after a few seconds.
Then, go to the automation's trace page, which you can access by navigating to Configuration->Automations->Click the clock icon in the relevant automation row.

From the automation's trace page post here screenshots + traces for all the automation runs which are generated by your interaction with the controller. You can navigate the recorded automation runs via the dropdown at the top of the page.

Thank you for your precious time and help!

**Comment by lebeno** [comment]
I am not very sure about your instructions, but here is a screen shot. Please let me know what particular extra information you need.
Schermafdruk van 2021-08-03 19-11-15

**Comment by EPMatt** [comment]
Hi @lebeno,
thank you for your feedback. From the image you posted it seems the event your device is firing when releasing the left button is different than the one you reported in the original issue (`release_5813`, while the blueprint is listening for the `release_1150` event).

I've just pushed a small fix for the blueprint. Could you please check if the updated version solves your issue with the left button?

Moreover, could you post here the screenshot of the same automation page, just after having released the right button?

Thank you!

**Comment by EPMatt** [comment]
Hi @lebeno,

While looking around for a solution for this issue, I came across this note (which I didn't remember about) on the project's documentation website regarding the E1810:

https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1524_e1810#issues-with-the-e1810-model-firing-bad-events

> It has been reported that the newer IKEA E1810 controller, which looks identical to the E1524, might fire wrong events in certain situations when interacting with it. This is due to an issue with the controller design and is not relative to the blueprint itself.
>
> If you notice your controller is not behaving as expected please remove the battery, wait about 2 minutes, insert it back and try again.

Could you please try to perform the suggested action and see if the issue is solved?

Thank you again. :)

**Pull request closed without merging**
