### PR TITLE
Fix detection of controller events with deCONZ

### LINKED ISSUE #42: IKEA E1812 Deconz not working
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to report a bug with a blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Bug Details\*

- Blueprint name: EPMatt/ikea_e1812.yaml
- Home Assistant Core Version: 2021.4.6
- Home Assistant Installation Type: Home Assistant Supervised

## Description\*

I have configured the controller for the e1812 with some simple actions (running a script) but it seems that the controller is not executing the configured actions.

## Automation YAML config\*

```yaml
alias: '[IKEA-Shortcut] Controller - Bertha Wohnzimmer saugen'
description: Lass Bertha das Wohnzimmer saugen
use_blueprint:
  path: EPMatt/ikea_e1812.yaml
  input:
    integration: deCONZ
    controller_device: 5c2adad9f497010a5d1cc7244401f1c8
    action_button_short:
      - service: script.bertha_wohnzimmer_saugen
      - condition: device
        device_id: cf31adae6946b68dc5796a8cfdf8606b
        domain: vacuum
        entity_id: vacuum.bertha
        type: is_cleaning
      - service: vacuum.pause
        target:
          entity_id: vacuum.bertha
    action_button_long:
      - service: script.bertha_stop
    action_button_double:
      - device_id: cf31adae6946b68dc5796a8cfdf8606b
        domain: vacuum
        entity_id: vacuum.bertha
        type: dock
    button_double_press: false
```

## To Reproduce\*

Steps to reproduce the issue:

1. Create a new automation from the blueprint
2. Add some actions
3. Trigger the automation
4. See that nothing happens

## Expected behavior\*

I would expect that the configured actions are running

## Actual Behaviour\*

Sscipts are not executed

## Additional Details\*

Calling the scripts without the automation is working as expected

## Screenshots

image

### PR DESCRIPTION
**Pull request by EPMatt**
Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Proposed change\*

Fix detection of controller events with deCONZ. This preserves the fix for double press events introduced in previous updates.
It works by converting `deconz_event` events payload into strings, ensuring all RAW events comparisons within the blueprint are valid and always involve two `string` operands. 

Closes #42.

## Checklist\*

- [X] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [ ] I properly tested proposed changes on my system and confirm that they are working as expected.
- [X] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

### CODE REVIEW

**Comment by EPMatt** [comment]
Hi @eloo,
could you please check if this PR solves the issue you reported?

Thanks!

**Comment by eloo** [comment]
Hi @EPMatt 
of course i will give it a try.
I will give feedback till the end of the day.

Thanks a lot

**Comment by eloo** [comment]
@EPMatt 
Hi seems that your change is not fixing the problem.
But i've figured out that when you wrap the trigger_action with string in the condition it seems to work (at least for deconz)

like this
```
      - conditions: "{{ (trigger_action | string)  in button_short }}"

```

**Comment by EPMatt** [comment]
@eloo I took some time to better understand why the fix does not work. I think the issue is in how Home Assistant renders variables in the `variables` script block. It looks like any numeric-like value, even if explicitly converted to string via the Jinja `string` filter, is converted into an int, thus making the fix I pushed yesterday completely useless.

I don't know whether this is an expected behaviour, but I'm now opening an issue on HA Core to report the problem.

Thank you very much for your test, that pointed me in the right direction. :) 
I'll fix the issue in a few minutes. 👍🏻

**Comment by EPMatt** [comment]
Hi @eloo, 
I've just pushed a fix for this issue.
Could you please check if the automation is now working as expected?

Thanks!

**Comment by eloo** [comment]
@EPMatt okay yes, an implicit type conversion sounds also unexpected to me.

i will give your fix a try in the evening.

Thanks!

**Comment by eloo** [comment]
@EPMatt 
its working as expected.

thanks

**Comment by EPMatt** [comment]
Hi @eloo,

Thank you for your feedback, I'm happy to hear that your issue is solved. :)
I'm now updating the changelog and merging this PR.

Thanks again

**Pull request merged**
